-- C-01: Make chat-media bucket private (no public URLs).
-- All access must go through signed URLs generated by authenticated users.

-- If the bucket already exists (created via dashboard), update it to be private.
-- If it does not exist, insert it.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM storage.buckets WHERE id = 'chat-media') THEN
    UPDATE storage.buckets
    SET public = false
    WHERE id = 'chat-media';
  ELSE
    INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
    VALUES (
      'chat-media',
      'chat-media',
      false,
      52428800, -- 50 MB
      ARRAY['image/jpeg','image/png','image/gif','image/webp','video/mp4','video/quicktime','audio/mpeg','audio/ogg','audio/webm','application/pdf']
    );
  END IF;
END $$;

-- Authenticated users can upload to their own folder (user_id prefix)
DROP POLICY IF EXISTS "chat_media_authenticated_insert" ON storage.objects;
CREATE POLICY "chat_media_authenticated_insert"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'chat-media'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- Authenticated users can read any chat-media object (group chats need cross-user reads)
DROP POLICY IF EXISTS "chat_media_authenticated_select" ON storage.objects;
CREATE POLICY "chat_media_authenticated_select"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (bucket_id = 'chat-media');

-- Authenticated users can delete only their own objects
DROP POLICY IF EXISTS "chat_media_authenticated_delete" ON storage.objects;
CREATE POLICY "chat_media_authenticated_delete"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'chat-media'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );
